version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(levelname)s - %(asctime)s - %(name)s -  %(message)s'

handlers:
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: app/logs/app.log
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

loggers:
  prod:
    level: DEBUG
    handlers: [file, console]
    propagate: no
